In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
import traceback
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
vacation_data_df = pd.read_csv('weather_data/weatherpy_challenge.csv')
vacation_data_df.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Current Description,Rain Inches (last 3 hrs),Snow Inches (last 3 hrs)
0,Klaksvik,62.23,-6.59,42.80,81,0,9.17,FO,2020-04-19 01-03:11,clear sky,0.00,0.0
1,Sampit,-2.53,112.95,75.36,98,100,0.89,ID,2020-04-19 01-01:07,moderate rain,4.39,0.0
2,Rikitea,-23.12,-134.97,77.49,69,21,6.42,PF,2020-04-19 01-03:18,few clouds,0.00,0.0
3,Tacarigua,10.09,-67.92,78.39,61,81,3.15,VE,2020-04-19 01-05:45,light rain,0.17,0.0
4,Bengkulu,-3.80,102.27,77.47,84,96,4.12,ID,2020-04-19 01-01:28,light rain,0.32,0.0

In [3]:
vacation_copy = vacation_data_df.copy()

In [4]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input('What is the minimum temperature you would like for your trip? '))
max_temp = float(input('What is the maximum temperature you would like for your trip? '))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [5]:
# Ask the customer if they want rain or snow.
rain = input('Do you want it to be raining? (y/n)')
snow = input('Do you want it to be snowing? (y/n)')

Do you want it to be raining? (y/n)n
Do you want it to be snowing? (y/n)n

In [6]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = vacation_copy.loc[(vacation_copy['Max Temp'] <= max_temp) & \
                                       (vacation_copy['Max Temp'] >= min_temp)]
if rain=='y':
    preferred_rain_df = preferred_cities_df.loc[(preferred_cities_df['Rain Inches (last 3 hrs)'])!=0]

else:
    preferred_rain_df = preferred_cities_df.loc[(preferred_cities_df['Rain Inches (last 3 hrs)'])==0]

if snow=='y':
    preferred_cities_df = preferred_rain_df.loc[(preferred_rain_df['Snow Inches (last 3 hrs)'])!=0]

else:
    preferred_cities_df = preferred_rain_df.loc[(preferred_rain_df['Snow Inches (last 3 hrs)'])==0]
preferred_cities_df.head(10)

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Current Description,Rain Inches (last 3 hrs),Snow Inches (last 3 hrs)
2,Rikitea,-23.12,-134.97,77.49,69,21,6.42,PF,2020-04-19 01-03:18,few clouds,0.0,0.0
10,Vaini,-21.20,-175.20,82.40,69,40,12.75,TO,2020-04-19 00-58:45,scattered clouds,0.0,0.0
11,Hithadhoo,-0.60,73.08,83.73,74,97,11.12,MV,2020-04-19 01-02:27,overcast clouds,0.0,0.0
17,Kapaa,22.08,-159.32,78.80,65,1,9.17,US,2020-04-19 01-03:19,clear sky,0.0,0.0
20,Boa Vista,2.82,-60.67,77.00,73,75,13.87,BR,2020-04-19 01-05:54,thunderstorm,0.0,0.0
28,Cabo San Lucas,22.89,-109.91,75.00,64,5,14.99,MX,2020-04-19 01-00:00,clear sky,0.0,0.0
32,Atuona,-9.80,-139.03,82.17,71,94,17.22,PF,2020-04-19 01-03:22,overcast clouds,0.0,0.0
35,Det Udom,14.91,105.08,89.01,78,47,5.55,TH,2020-04-19 01-06:01,scattered clouds,0.0,0.0
50,Vao,-22.67,167.48,76.46,68,48,9.55,NC,2020-04-19 01-02:27,scattered clouds,0.0,0.0
54,Kuliyapitiya,7.47,80.04,77.00,100,20,2.24,LK,2020-04-19 01-06:11,few clouds,0.0,0.0

In [7]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[['City', 'Country', 'Max Temp', 'Current Description','Lat','Lng']].copy()
hotel_df['Hotel Name'] = ''
hotel_df['Current Description']=hotel_df['Current Description'].str.capitalize()
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Rikitea,PF,77.49,Few clouds,-23.12,-134.97,
10,Vaini,TO,82.40,Scattered clouds,-21.20,-175.20,
11,Hithadhoo,MV,83.73,Overcast clouds,-0.60,73.08,
17,Kapaa,US,78.80,Clear sky,22.08,-159.32,
20,Boa Vista,BR,77.00,Thunderstorm,2.82,-60.67,
...,...,...,...,...,...,...,...
543,Banda Aceh,ID,79.81,Broken clouds,5.56,95.32,
544,Doha,QA,75.99,Broken clouds,25.29,51.53,
551,Pringsewu,ID,76.28,Overcast clouds,-5.36,104.97,
558,Nieuw Nickerie,SR,80.62,Broken clouds,5.95,-56.98,
568,Princeton,US,80.60,Clear sky,25.54,-80.41,

In [8]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude
    lat = row['Lat']
    lng = row['Lng']

    # Add the latitude and longitude to location key for the params dictionary.
    params = {"radius": 5000,"type": "lodging","key": g_key,'location':f'{lat},{lng}'}
    # Use the search term: "lodging" and our latitude and longitude.
    base_url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json'
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    hotels
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, 'Hotel Name'] = hotels['results'][0]['name']
    except (IndexError):
        traceback.print_exc()
        print('Hotel not found...skipping.')

Traceback (most recent call last):
  File "<ipython-input-8-2c360d42ae5c>", line 16, in <module>
    hotel_df.loc[index, 'Hotel Name'] = hotels['results'][0]['name']
IndexError: list index out of range

Hotel not found...skipping.

Traceback (most recent call last):
  File "<ipython-input-8-2c360d42ae5c>", line 16, in <module>
    hotel_df.loc[index, 'Hotel Name'] = hotels['results'][0]['name']
IndexError: list index out of range

Hotel not found...skipping.

Traceback (most recent call last):
  File "<ipython-input-8-2c360d42ae5c>", line 16, in <module>
    hotel_df.loc[index, 'Hotel Name'] = hotels['results'][0]['name']
IndexError: list index out of range

Hotel not found...skipping.

Traceback (most recent call last):
  File "<ipython-input-8-2c360d42ae5c>", line 16, in <module>
    hotel_df.loc[index, 'Hotel Name'] = hotels['results'][0]['name']
IndexError: list index out of range

Hotel not found...skipping.

Traceback (most recent call last):
  File "<ipython-input-8-2c360d42ae5c>", line 16, in <module>
    hotel_df.loc[index, 'Hotel Name'] = hotels['results'][0]['name']
IndexError: list index out of range

Hotel not found...skipping.

Traceback (most recent call last):
  File "<ipython-input-8-2c360d42ae5c>", line 16, in <module>
    hotel_df.loc[index, 'Hotel Name'] = hotels['results'][0]['name']
IndexError: list index out of range

Hotel not found...skipping.

Traceback (most recent call last):
  File "<ipython-input-8-2c360d42ae5c>", line 16, in <module>
    hotel_df.loc[index, 'Hotel Name'] = hotels['results'][0]['name']
IndexError: list index out of range

Hotel not found...skipping.

Traceback (most recent call last):
  File "<ipython-input-8-2c360d42ae5c>", line 16, in <module>
    hotel_df.loc[index, 'Hotel Name'] = hotels['results'][0]['name']
IndexError: list index out of range

Hotel not found...skipping.

In [13]:
# Hotel Locations
# Get the latitude and longitude.
locations = hotel_df[["Lat", "Lng"]]
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} at {Max Temp} F Degrees</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Add markers.
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)

# Add the marker layer.
fig.add_layer(markers)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Rikitea,PF,77.49,Few clouds,-23.12,-134.97,Pension Maro'i
10,Vaini,TO,82.40,Scattered clouds,-21.20,-175.20,Keleti Beach Resort
11,Hithadhoo,MV,83.73,Overcast clouds,-0.60,73.08,Scoop Guest House
17,Kapaa,US,78.80,Clear sky,22.08,-159.32,Sheraton Kauai Resort at Coconut Beach
20,Boa Vista,BR,77.00,Thunderstorm,2.82,-60.67,Aipana Plaza Hotel
...,...,...,...,...,...,...,...
543,Banda Aceh,ID,79.81,Broken clouds,5.56,95.32,OYO 884 Rumoh PMI Hotel
544,Doha,QA,75.99,Broken clouds,25.29,51.53,Ezdan Hotel
551,Pringsewu,ID,76.28,Overcast clouds,-5.36,104.97,Urban Style by Front One
558,Nieuw Nickerie,SR,80.62,Broken clouds,5.95,-56.98,Ishwardat Inn
568,Princeton,US,80.60,Clear sky,25.54,-80.41,American Best Inn

In [11]:
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Rikitea,PF,77.49,Few clouds,-23.12,-134.97,Pension Maro'i
10,Vaini,TO,82.40,Scattered clouds,-21.20,-175.20,Keleti Beach Resort
11,Hithadhoo,MV,83.73,Overcast clouds,-0.60,73.08,Scoop Guest House
17,Kapaa,US,78.80,Clear sky,22.08,-159.32,Sheraton Kauai Resort at Coconut Beach
20,Boa Vista,BR,77.00,Thunderstorm,2.82,-60.67,Aipana Plaza Hotel
...,...,...,...,...,...,...,...
543,Banda Aceh,ID,79.81,Broken clouds,5.56,95.32,OYO 884 Rumoh PMI Hotel
544,Doha,QA,75.99,Broken clouds,25.29,51.53,Ezdan Hotel
551,Pringsewu,ID,76.28,Overcast clouds,-5.36,104.97,Urban Style by Front One
558,Nieuw Nickerie,SR,80.62,Broken clouds,5.95,-56.98,Ishwardat Inn
568,Princeton,US,80.60,Clear sky,25.54,-80.41,American Best Inn

In [12]:
hotel_df.to_csv('C:/Users/phsstudent/Desktop/Data_Analytics/Class/World_Weather_Analysis/weather_data/weatherpy_vacation.csv', index=False)